### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Booker#14]
We would like to have the same README format across the projects for Evil Bees. 
Example of the good README is for AlertIt project.
https://github.com/Evil-Bees/Alertit/blob/main/README.md

We would like to copy this README to Booker and update with missing information.

Technologies used for Booker:
- Next.js
- Material UI
- Mongo DB

**Comment by Rishav1707** [comment]
Shall I work on this issue? @nikolap994

**Comment by nikolap994** [comment]
You are welcome to do so :)
